<?php
require_once('admin_init_ver.php');
update_option('mdx_night_style', 'true');
update_option('mdx_auto_night_style', 'true');
update_option('mdx_notice', '');
update_option('mdx_open_side', 'true');
update_option('mdx_img_box', 'true');
update_option("mdx_readmore", __('去围观', 'mdx'));
update_option("mdx_post_money", '');
update_option("mdx_lazy_load_mode", 'speed');
update_option('mdx_read_pro', 'true');
update_option('mdx_pro_save', 'true');
update_option('mdx_auto_scroll', 'false');
update_option('mdx_load_pro', 'true');
update_option('mdx_post_list_1', 'view');
update_option('mdx_post_list_2', 'time');
update_option('mdx_post_edit_time', 'post');
update_option('mdx_author_card', 'false');
update_option('mdx_speed_pre', 'false');
update_option('mdx_smooth_scroll', 'false');
update_option('mdx_share_area', 'all');
update_option('mdx_tap_to_top', 'true');
update_option('mdx_hot_posts', 'false');
update_option('mdx_hot_posts_num', '10');
update_option('mdx_hot_posts_cat', '');
update_option('mdx_hot_posts_text', __('推荐文章','mdx'));
update_option('mdx_all_posts_text', __('最新文章','mdx'));
update_option('mdx_you_may_like', 'false');
update_option('mdx_you_may_like_way', 'tag');
update_option('mdx_you_may_like_text', __('推荐文章', 'mdx'));
update_option('mdx_real_search', 'false');
update_option('mdx_comment_ajax', 'true');
update_option('mdx_seo_key', '');
update_option('mdx_auto_des', 'true');
update_option('mdx_seo_des', '');
update_option('mdx_head_js', '');
update_option('mdx_footer_js', '');
?>