<?php
update_option('mdx_styles', 'indigo');
update_option('mdx_styles_hex', '#3f51b5');
update_option('mdx_styles_act', 'pink');
update_option('mdx_act_hex', '#ff4081');
update_option('mdx_chrome_color', 'true');
update_option('mdx_title_bar', 'false');
update_option('mdx_title_med', 'wp');
update_option('mdx_default_style', '1');
update_option('mdx_index_show', '0');
update_option('mdx_post_style', '0');
update_option('mdx_echo_post_sum', 'ture');
update_option('mdx_post_def_img', 'false');
update_option('mdx_index_img', get_bloginfo("template_url").'/img/def_index.jpg');
update_option('mdx_side_img', get_bloginfo("template_url").'/img/def_side.jpg');
update_option('mdx_side_info', 'false');
update_option('mdx_side_head', '');
update_option('mdx_side_name', '');
update_option('mdx_side_more', '');
update_option('mdx_index_say', 'Hello, MDx!');
update_option('mdx_comment_emj', 'true');
update_option('mdx_say_after', '');
update_option('mdx_index_say_size', '1');
update_option('mdx_logo_way', '1');
update_option('mdx_logo', '');
update_option('mdx_logo_text', '');
update_option('mdx_safari', 'false');
update_option('mdx_svg', '');
update_option('mdx_svg_color', '');
update_option('mdx_footer_say', 'Hello, MDx!');
update_option('mdx_footer', '');
?>